### ISSUE TITLE
Bash Discussion

### ISSUE THREAD

**Issue by alexdantas** [bpkg/bpkg#12]
`bpkg` is a nice initiative, both to stimulate Bash scripting and create a standard way of serving Bash programs.

Here I'll share some interesting links regarding Bash that we might include on the documentation, website or whatever. At least they might be useful for us, Bash beginners.

I hope everyone can join in and discuss more Bash-related stuff.
- [bashlint and ShellCheck for checking Bash sources](http://blog.yjl.im/2014/06/bashlint-and-shellcheck-for-checking.html): Interesting to apply to our own scripts before releasing;
- [Bash Style Guide and Coding Standard](http://www.reddit.com/r/programming/comments/27nuc6/coding_and_shell_standards_as_a_newbie_no_one/): Although it has some redundant parts, it might be useful for beginners;

**Comment by Potherca** [comment]
At my current employers we were lacking a definitive style guide for BASH so we build one (mostly based on standing conventions): http://guides.dealerdirect.io/code-styling/bash/

I would be interested to see if it is usable for common conventions beyond out company.

**Comment by Potherca** [comment]
Besides my previous comment I think it would be good to have an page documenting some common conventions and best practices to help people write better BASH scripts.

Using Shellcheck should definitely be on that list! 😸

**Comment by jwerle** [comment]
@Potherca that sounds great!

**Comment by Potherca** [comment]
Closing this issue as the deliverable is not clear and activity for this issue is low.

Feel free to re-open this issue or open a new one with a more clear objective or plan.
