### ISSUE TITLE
SSL for get.bpkg.sh

### ISSUE THREAD

**Issue by francescobianco** [bpkg/bpkg#121]
If I try to install with CURL from HTTPS it still pending because no HTTPS is supported

```bash
$ curl -sLo- https://get.bpkg.sh | bash
```

not work by HTTPS protocol

**Comment by Potherca** [comment]
Until this is resolved, the best workaround is to curl to the source, as `http://get.bpkg.sh` is basically just a redirect:

```
curl -sLo- https://raw.githubusercontent.com/bpkg/bpkg/master/setup.sh | bash
```

**Comment by Potherca** [comment]
@jwerle Is there much work involved to set up SSL for `get.bpkg.sh`? And/Or is there any way I can assist?

**Comment by francescobianco** [comment]
Today my solution for a similar project was based on a Caddy server used as a proxy in a cheap VPS

This is the codebase for the proxy
https://github.com/javanile/ionos-proxy

This is a project using the proxy
https://github.com/javanile/binst.tk

**Comment by jwerle** [comment]
@Potherca I think we can just have the `get.bpkg.sh` CNAME and domain set for https://github.com/bpkg/bpkg

**Comment by jwerle** [comment]
@Potherca actually it won't be that simple :(
