### ISSUE TITLE
Calling all Admins! Who's still on board?

### ISSUE THREAD

**Issue by Potherca** [bpkg/bpkg#126]
Currently, the BPKG org has 22 admin users. Looking at the (lack of) contribution, should we bring that number down to active members?

Or at least move people into groups so it is more clear who can be counted on for review/merge/etc?

Maybe everyone could respond as to whether they are still interested in being part of BPKG?

To be clear: I am not looking to push people out of the org, this is about making an inventory and getting a more clear idea of expectations and availability.

**If you don't have the time or energy to contribute but would still prefer to remain part of the org, that is perfectly fine!**

## Stay as Admin

 - [x] @francescobianco
 - [x] @jwerle
 - [x] @Potherca

## Stay, but not as Admin

 - [x] @bcomnes
 - [x] @benkogan
 - [x] @brock
 - [x] @ccarpita
 - [x] @humanshell
 - [x] @juliangruber
 - [x] @Prash74
 - [x] @rylnd
 - [x] @stephenmathieson
 - [x] @vipyne
 - [x] @wellsjo
 - [x] @yields
 - [x] @yorkie

## Awaiting Response

  - [ ] @agrathwohl
  - [ ] @alexdantas
  - [ ] @heapwolf
  - [ ] @isaacs
  - [ ] @jb55
  - [ ] @rauchg

**Comment by stephenmathieson** [comment]
I do not need to be an admin.

**Comment by francescobianco** [comment]
I would like to keep the Admin status, I know that for this year I cannot actively contribute, unfortunately due to the pandemic I had to reduce the work on LCOV, but I hope soon to be 100% on BASH and LCOV again.

**Comment by juliangruber** [comment]
I do not need to be an admin either 🙇

**Comment by brock** [comment]
I do not need to be an admin either. Happy to continue on as part of the team, but smart for you to be reducing the controls. 👍

**Comment by wellsjo** [comment]
you can take me off admin as well

**Comment by bcomnes** [comment]
Stay on, not admin.

**Comment by yorkie** [comment]
Stay on, not admin.

**Comment by rylnd** [comment]
I'd like to stay in the org for the possibility of contributing, but I don't need to be an admin 👍

**Comment by humanshell** [comment]
i do not need to be an admin

**Comment by Prash74** [comment]
I do not need to be an admin

**Comment by vipyne** [comment]
I'd like to stay on, but do not need to be admin.

**Comment by benkogan** [comment]
I can be removed from admin as well. Thanks!

**Comment by yields** [comment]
Same, I can be eliminated :)

**Comment by ccarpita** [comment]
I can be removed as well, thanks!

**Comment by Potherca** [comment]
Thanks to everyone who has responded thus far!

Friendly reminder to @agrathwohl, @alexdantas, @heapwolf, @isaacs, @jb55, and @rauchg to respond if they are able.

**Comment by Potherca** [comment]
After two weeks grace period since my previous message, I have concluded the following actions:

- All [organization members](https://github.com/orgs/bpkg/people) have been given role "Member", except for @francescobianco @jwerle and myself (@Potherca) whom have been given roll "Owner"

- Three teams have been created (to make it easier to draw the attention of certain groups of people):  
   - @bpkg/admins - This is the same as the role "Owner"
   - @bpkg/contributors - This is the same as the role "Member"
   - @bpkg/maintainers - This is a list of Owners or Members that are currently most active in maintaining BPKG<br> <sup>(currently @bcomnes @francescobianco @jwerle @Potherca @Prash74)</sup>

- All people in a team are admin for that team

If I have missed anything or if you have any other feedback, please let me know. If there is no major opposition or open tasks present, I will close this issue in 10 days (2020-02-14).
