### ISSUE TITLE
Bug: pathspec 'master' did not match any file(s) known to git

### ISSUE THREAD

**Issue by NNBnh** [bpkg/bpkg#130]
<b>
<kbd>EDIT BY MAINTAINERS:</kbd>

Because of the recent trend of renaming a repository's `master` branch to `main`, users of BKPG might encounter this error:

> pathspec 'master' did not match any file(s) known to git

We have acknowledged this is a serious bug which should be addressed as soon as possible. Please bear with us while we sort out a solution.

The current workaround is to explicitly specify the branch name when installing:

```sh
bpkg install example/repo@main
```
</b>

 - - -

<kbd>ORIGINAL ISSUE:</kbd>

Hi, i'm the developer of [**SuperB Fetch**](https://github.com/NNBnh/bfetch) and i found `bpkg` to be a perfect package manager for my project.

But i'm confused when try to install it:
```
bpkg install NNBnh/bfetch
```

It output:
```console
    info: Install /NNBnh/bfetch/master from remote https://raw.githubusercontent.com [https://github.com]
    info: Cloning https://github.com/NNBnh/bfetch.git to superbfetch-master
Cloning into 'superbfetch-master'...
remote: Enumerating objects: 206, done.
remote: Counting objects: 100% (206/206), done.
remote: Compressing objects: 100% (172/172), done.
remote: Total 206 (delta 96), reused 94 (delta 30), pack-reused 0
Receiving objects: 100% (206/206), 246.87 KiB | 380.00 KiB/s, done.
Resolving deltas: 100% (96/96), done.
error: pathspec 'master' did not match any file(s) known to git
```

Here is the [`package.json`](https://github.com/NNBnh/bfetch/blob/main/package.json) and the [`Makefile`](https://github.com/NNBnh/bfetch/blob/main/Makefile)

My theory is that because my package is also try to be compatible with [Basher's packaging structure](https://github.com/basherpm/basher#packages) so it bug out...
> Any files inside a `bin` directory are added to the path. If there is no bin directory, any executable files in the package root are added to the path.
>
> Any manpages (files ended in `\.[0-9]`) inside a `man` directory are added to the manpath.

Can you guy take a look, thank you.

**Comment by Potherca** [comment]
Hi, Thank you for taking the time to report this issue!

It looks like the problem is caused because BPKG has [`master` hard-coded as default branch](https://github.com/bpkg/bpkg/blob/HEAD/lib/install/install.sh#L242) if no version constraint has been provided when `bpkg install` is called. As `NNBnh/bfetch` uses the more contemporary convention of having `main` as default branch, the `git clone` command fails, since BPKG [tacks the branch (or version) onto the clone command](https://github.com/bpkg/bpkg/blob/HEAD/lib/install/install.sh#L402).

The fix, I think, would be to not have BPKG use a branch or version constraint if/when none is given. I haven't been in the `install` code for a while, so I can't give you a timefrime, but this is _definitely_ a bug that needs to be fixe ASAP!

**Comment by jwerle** [comment]
@Potherca what are your thoughts on support both `master` and `main` as default branches? We could try `master` falling back `main` or vice versa

**Comment by Potherca** [comment]
I'll have to run some tests, but if we can't get away with not specifying a branch or version constraint, I'd say going for `master` and then `main` as a fallback is the sanest approach.

**Comment by francescobianco** [comment]
I hope it goes as solution for the problem <https://github.com/bpkg/bpkg/pull/138>

**Comment by jwerle** [comment]
@Potherca @francescobianco is this safe to close?

**Comment by Potherca** [comment]
It think it dependes on whether we also need to do other work, beyond the install, for the whole `main` vs. `master` thing. Not sure, currently.

**Comment by francescobianco** [comment]
I just create a public test for installing NNBnh/bfetch please review

- <https://replit.com/@frabik/BPKG-Testing-issue-130#main.sh>

It works PERFECT!!!
@NNBnh @jwerle @Potherca 
For me the issue could be closed

**Comment by jwerle** [comment]
wonderful!
