### ISSUE TITLE
Feature request: install multiple packages with one command

### ISSUE THREAD

**Issue by NNBnh** [bpkg/bpkg#131]
Hello, i'm the developer of [SBB (SuperB Bootstrap)](https://github.com/NNBnh/superb-bootstrap) and i would like to add BPKG package manager support to [SBB setup script](https://github.com/NNBnh/superb-bootstrap/issues/5). But after looking around, their seem to be no way to install multiple package in one command with BPKG like this:

```sh
bpkg install USER/PACKAGE1 USER/PACKAGE2 USER/PACKAGE3 ...
```

Do i missing something? Help...

**Comment by Potherca** [comment]
Hi! You didn't miss anything... BPKG currently does not support installing multiple packages in one call. It would be a cool feature to have, though!

**Comment by jwerle** [comment]
we now have this!
