### ISSUE TITLE
docs: copy command wrong

### ISSUE THREAD

**Issue by sinkcup** [bpkg/bpkg#135]
![image](https://user-images.githubusercontent.com/4971414/129309869-b0adf5ed-8a9d-453c-af9c-a052c3656584.png)
![image](https://user-images.githubusercontent.com/4971414/129309969-0b9be6c1-5b11-444d-af69-6b8380dcdb75.png)

if click the copy icon, result will be wrong.

**Comment by Potherca** [comment]
Resolved in #136
