### ISSUE TITLE
JSON Schema definition and bpkg.json documentation

### ISSUE THREAD

**Issue by Potherca** [bpkg/bpkg#142]
Now `bpkg.json` has been implemented, we might want to add more documentation regarding the allowed/accepted keys and expected values.

It would also be helpful to have a [JSON-Schema](https://json-schema.org/) definition, to allow auto-completion and validation of `bpkg.json` files in other tools, editors and IDEs.

## JSON Schema

We could also quite easily generate a JSON-Schema and manually adjust things to match our demands.

Taking this as a basis:

```json
{
  "name": "term",
  "version": "0.0.1",
  "description": "Terminal utility functions",
  "global": "true",
  "install": "make install",
  "scripts": [ "term.sh" ],
  "files": ["bar.txt", "foo.txt"],
  "dependencies": {
    "term": "0.0.1"
  }
}
```

A randomly chosen [JSON Schema generator](https://extendsclass.com/json-schema-validator.html) gives us this:

<details>
<summary>Generated JSON Schema</summary>

```json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#", 
	"$id": "https://example.com/object1648395826.json", 
	"title": "Root", 
	"type": "object",
	"required": [
		"name",
		"version",
		"description",
		"global",
		"install",
		"scripts",
		"files",
		"dependencies"
	],
	"properties": {
		"name": {
			"$id": "#root/name", 
			"title": "Name", 
			"type": "string",
			"default": "",
			"examples": [
				"term"
			],
			"pattern": "^.*$"
		},
		"version": {
			"$id": "#root/version", 
			"title": "Version", 
			"type": "string",
			"default": "",
			"examples": [
				"0.0.1"
			],
			"pattern": "^.*$"
		},
		"description": {
			"$id": "#root/description", 
			"title": "Description", 
			"type": "string",
			"default": "",
			"examples": [
				"Terminal utility functions"
			],
			"pattern": "^.*$"
		},
		"global": {
			"$id": "#root/global", 
			"title": "Global", 
			"type": "string",
			"default": "",
			"examples": [
				"true"
			],
			"pattern": "^.*$"
		},
		"install": {
			"$id": "#root/install", 
			"title": "Install", 
			"type": "string",
			"default": "",
			"examples": [
				"make install"
			],
			"pattern": "^.*$"
		},
		"scripts": {
			"$id": "#root/scripts", 
			"title": "Scripts", 
			"type": "array",
			"default": [],
			"items":{
				"$id": "#root/scripts/items", 
				"title": "Items", 
				"type": "string",
				"default": "",
				"examples": [
					"term.sh"
				],
				"pattern": "^.*$"
			}
		},
		"files": {
			"$id": "#root/files", 
			"title": "Files", 
			"type": "array",
			"default": [],
			"items":{
				"$id": "#root/files/items", 
				"title": "Items", 
				"type": "string",
				"default": "",
				"examples": [
					"bar.txt"
				],
				"pattern": "^.*$"
			}
		},
		"dependencies": {
			"$id": "#root/dependencies", 
			"title": "Dependencies", 
			"type": "object",
			"required": [
				"term"
			],
			"properties": {
				"term": {
					"$id": "#root/dependencies/term", 
					"title": "Term", 
					"type": "string",
					"default": "",
					"examples": [
						"0.0.1"
					],
					"pattern": "^.*$"
				}
			}
		}

	}
}
```

</details>

**Comment by hyperupcall** [comment]
Once the schema file is added here, I can add a sort of redirect to it at [schemastore](https://github.com/SchemaStore/schemastore), so things Just Work for code editors and IDEs

**Comment by hyperupcall** [comment]
A few days ago I added a schema at [schemastore.org](https://json.schemastore.org/bpkg.json). Feel free to make updates

**Comment by jwerle** [comment]
> A few days ago I added a schema at [schemastore.org](https://json.schemastore.org/bpkg.json). Feel free to make updates through follow-up PRs.

very well! we'd happily review a PR to add this to the repository

**Comment by hyperupcall** [comment]
@jwerle I hosted the schema on SchemaStore rather than here to take advantage of the existing infrastructure and schema improvements we've been doing upstream.

But if you're committed to maintaining the schema here, feel free to move the schema here and send a PR to SchemaStore to add a redirect.

**Comment by hyperupcall** [comment]
In any case, IDEs still automatically show recommendations and completions for `bpkg.json`

**Comment by hyperupcall** [comment]
Usually I prefer hosting things at SchemaStore since it's usually easier for schemas to be improved that way.

But in the end, the choice is yours, which is why we have a policy for redirecting to schemas hosted elsewhere.

**Comment by jwerle** [comment]
awesome well lets just keep it on SchemaStore unless we have a strict need to maintain it here

**Comment by hyperupcall** [comment]
Sounds good

**Comment by hyperupcall** [comment]
shall this issue be closed then

**Comment by jwerle** [comment]
> shall this issue be closed then

Yeah let's close it
