### ISSUE TITLE
Install a specific version

### ISSUE THREAD

**Issue by francescobianco** [bpkg/bpkg#145]
At this moment the file 'setup.sh' is not related to a specific tag/version. As a result of this, both the following, install the same version (master in the case)

```shell
curl -sL https://raw.githubusercontent.com/bpkg/bpkg/1.0.6/setup.sh | bash
```

```shell
curl -sL https://raw.githubusercontent.com/bpkg/bpkg/1.0.12/setup.sh | bash
```

This is because the line used to clone is pointing to master in all cases

https://github.com/bpkg/bpkg/blob/master/setup.sh#L51

I suggest to amends all TAGS in a way to have all setup.sh able to point to the proper version

I try to do this manually to test the version '1.0.0'

See my amends commits here https://github.com/bpkg/bpkg/commits/1.0.0

**Comment by jwerle** [comment]
that sounds good to me!

**Comment by jwerle** [comment]
@francescobianco i've used this script https://gist.github.com/jwerle/5f937115818b76712efca575c73b8a9f to do this

You can now do:

```sh
curl -Lo- get.bpkg.sh | TAG=0.3.2 bash
```
or 

```sh
curl -Lo- "https://raw.githubusercontent.com/bpkg/bpkg/0.3.2/setup.sh" | bash
```

**Comment by thackel** [comment]
I don't think that this is properly working anymore. The script is no longer on the path.

This will demonstrate it:
`docker run --rm -it centos:7.9.2009 bash -c "yum -y update && yum -y install curl git && curl -Lo- "https://raw.githubusercontent.com/bpkg/bpkg/1.0.15/setup.sh" | bash && bpkg"`

Also older versions (0.3.2, 0.3.1) will not work.

**Comment by jwerle** [comment]
@Potherca I rewrote the history and fixed it. the `$USER` variable was not available in the `setup.sh` script so I used the `whoami` command instead. I've tested locally with docker and can confirm it works now
