### ISSUE TITLE
1.0.20 cause install command hung there

### ISSUE THREAD

**Issue by JoeyLi-1** [bpkg/bpkg#147]
Hi there,

We just encounter this issue 5 hours ago.
We run command "
curl -Lo- "https://raw.githubusercontent.com/bpkg/bpkg/master/setup.sh" | sudo bash
sudo bpkg install -g sstephenson/bats" on CircleCI. (OS: Ubuntu)
The install command just hung there. 

If I revert back to 1.0.16 (curl -Lo- "https://raw.githubusercontent.com/bpkg/bpkg/1.0.16/setup.sh" | sudo bash)
Everything works fine.

Do not know what happened. Since I tried "-v or -V" but there is no detail output. I tried without sudo it did works fine.
So, bpkg list -> works
sudo bpkg list -> hung
sudo bpkg list -v -> hung
sudo bpkg list -V -> hung

Just want to report this issue, please help to double check. Thank you!

**Comment by jwerle** [comment]
thank you for the report!
fixed in https://github.com/bpkg/bpkg/commit/1b097711a8606e68371cb1860d91e122d6a22c11
