### ISSUE TITLE
asdf plugin

### ISSUE THREAD

**Issue by jwerle** [bpkg/bpkg#148]
It could be nice to support [asdf](https://asdf-vm.com/) with a plugin. We can give `asdf` users the ability to manage versions of `bpkg` on their systems. It looks pretty straightforward: https://github.com/asdf-vm/asdf-plugin-template

**Comment by jwerle** [comment]
cc @Potherca @francescobianco

**Comment by Potherca** [comment]
Personally, I don't have the bandwidth to research or implement this but I do think it could be worth the effort.

The more places BPKG is available, the more likely it is to be more widely adapted, I think.

Would #90 have to be done for this, or is `asdf` fine with running BASH?

**Comment by francescobianco** [comment]
Hi @Potherca @jwerle please let me build as my tangible contribution! I'm able to release it inside april!
Let's choose the name of the repository together. This is my proposal: https://github.com/bpkg/asdf-bpkg

**Comment by jwerle** [comment]
> Hi @Potherca @jwerle please let me build this as my tangible contribution! I'm able to release it inside april! Let's choose the name of the repository together. This is my proposal: https://github.com/bpkg/asdf-bpkg

This sounds good to me!

> At the same time I propose to create a mirror/fork of 'asdf' project enabling people run this as useful:
> 
> ```shell
> bpkg install asdf
> ```

We're already doing it here: https://github.com/bpkg/macos-virtualbox
https://github.com/bpkg/semver-tool


> In this case due to 'asdf' is large project hard to keep updated into our fork. I propose to create a small repository with just few file (obvisuly bpkg.json) that installing not the fork itself but the official one from the https://github.com/asdf-vm/asdf We can call this tecnique 'proxy installation'. Does that make sense?

**Comment by jwerle** [comment]
this is done!
