### ISSUE TITLE
Branch for old version seem to be missing

### ISSUE THREAD

**Issue by thackel** [bpkg/bpkg#150]
The latest changes either in code or the repository have again made the setup fail.

Pulling and executing `curl -Lo- "https://raw.githubusercontent.com/bpkg/bpkg/0.3.1/setup.sh" | bash`
Raises the following problems (removed just the piping to /dev/null to see the problems):
```
Cloning into '/tmp/bpkg- 0.3.1'...
warning: Could not find remote branch  0.3.1 to clone.
fatal: Remote branch  0.3.1 not found in upstream origin
Unexpected end of command stream
./file: line 56: cd: /tmp/bpkg- 0.3.1: No such file or directory
```

The tag "0.3.1" is still existing and a manual checkout works.
I think there is a SPACE/BLANK extracted before the version number, and this will result in ` 0.3.1` which does not exist...

**Comment by Potherca** [comment]
>  I think there is a SPACE/BLANK extracted before the version number, and this will result in ` 0.3.1` which does not exist...

I think you are correct. Debugging now...

**Comment by Potherca** [comment]
The `TAG` definition for the `0.3.1` is broken:

https://github.com/bpkg/bpkg/blob/0.3.1/setup.sh#L12

```sh
VERSION=" "0.3.1""
```

That should be:

```
VERSION="0.3.1"
```

Patching now.

**Comment by jwerle** [comment]
fixed in https://github.com/bpkg/bpkg/commit/7f3aa1f5e7c4774f484005d6b3c4b5875cfd822f

**Comment by jwerle** [comment]
I am going to setup an action that will test every version so things like this can be caught

**Comment by Potherca** [comment]
@jwerle I left a debugging comment at [the `file-fix-tag-history.sh` gist](https://gist.github.com/jwerle/5f937115818b76712efca575c73b8a9f) that could be relevant. Could you check?

**Comment by jwerle** [comment]
> @jwerle I left a debugging comment at [the `file-fix-tag-history.sh` gist](https://gist.github.com/jwerle/5f937115818b76712efca575c73b8a9f) that could be relevant. Could you check?

I am hoping https://github.com/bpkg/bpkg/commit/7f3aa1f5e7c4774f484005d6b3c4b5875cfd822f#diff-1926f3667e08c763d9912b76e8990bb45ee98cc5aaf101eacd130e546bb1e78dR17 fixes that

CI tests coming soon for full verification so this never happens again 😓

**Comment by jwerle** [comment]
okay I hope https://github.com/bpkg/bpkg/pull/151 fixes this

**Comment by thackel** [comment]
Thanks for the quick reaction, it's working again!

**Comment by jwerle** [comment]
> Thanks for the quick reaction, it's working again!

thanks for letting us know!
