### ISSUE TITLE
Feature Request: Install Dependencies for Development

### ISSUE THREAD

**Issue by samlikins** [bpkg/bpkg#157]
Using BPKG for projects aids in the development and deployment process, however a key component seems to be lacking.  While a project may require dependencies (and BPKG provides a feature for defining and installing said dependent packages), packages which may be required during development (but not for deployment) _currently_ still need to be defined in the same location as the production dependencies (ie: `dependencies` array in the BPKG package file) or installed separately.

A separate array of dependencies just for development in the BPKG package file would satisfy this requirement, without negatively affecting normal install processes.  To perform an install of the development dependencies, a command line flag could be provided during normal install to include the additional needed development packages in addition to the normal requirements.

Cursory review of the BPKG tool provides a format which if followed the following suggestions could be used to implement this feature request.

- Package file array `dependencies-dev` being added for listing development requirements
- BPKG utility flag `-d` or `--dev` being added to the install command for including the defined development requirements

**Comment by samlikins** [comment]
Pull Request #158 has been generated as an offering as to how this feature request could be implemented and documentation for suggested implementation for has [bpkg.github.io pull request #63](https://github.com/bpkg/bpkg.github.io/pull/63)

**Comment by jwerle** [comment]
we've needed this for a while. thank you!

**Comment by samlikins** [comment]
@jwerle: Did my arbitrary suggested changes actually perform the correct steps to implement this feature?

**Comment by jwerle** [comment]
> @jwerle: Did my arbitrary suggested changes actually perform the correct steps to implement this feature?

yep!
