### ISSUE TITLE
bkpg --help : basename: invalid option -- 'a'

### ISSUE THREAD

**Issue by juanpabloaj** [bpkg/bpkg#36]
when I try `bpkg --help`

```sh
$ bpkg --help

  usage: bpkg [-hV] <command> [args]

Here are some commands available in your path:

basename: invalid option -- 'a'
Try `basename --help' for more information.
```

my basename version

```sh
$ basename --version
basename (GNU coreutils) 8.13
```

**Comment by coderaiser** [comment]
Everything works good in my environment.
```sh
coderaiser@cloudcmd:~/cloudcmd$ basename --version
basename (GNU coreutils) 8.21
```

`basename` [used in this code](https://github.com/bpkg/bpkg/blob/6c5079c099ee79012cd08457e8133c1b5d07e13f/bpkg.sh#L24) to get list of commands.
```sh
## commands
commands () {
  {
    declare -a local cmds=( $(
      bpkg-suggest 'bpkg-' |
      tail -n+2            |
      xargs basename -a    |
      sort -u              |
      sed 's/bpkg-//g'     |
      tr '\n' ' '
    ) )

    echo "${cmds[@]}"
  }
}
```

Maybe there is a solution to get this list without use of `basename`?

**Comment by juanpabloaj** [comment]
I have basename version 8.13

```sh
$ basename --version
basename (GNU coreutils) 8.13
```

after this commit (2012-03-04 19:00:36 (GMT))

http://git.savannah.gnu.org/cgit/coreutils.git/commit/?id=a3eb71a98fd195e52d335fb8d6bdc2a719cc2c88

basename get the argument `-a`

**Comment by juanpabloaj** [comment]
like say @coderaiser maybe a solution is get the list without basename, or in section install of readme file say the dependencies of bpkg: bash version, coreutils version, etc.

**Comment by jwerle** [comment]
We'd happily accept a PR. We've seen this issue before. I unfortunately do no have the time atm to issue a patch :/

cc @stephenmathieson @ccarpita
