### ISSUE TITLE
How to require dependencies? 

### ISSUE THREAD

**Issue by awei01** [bpkg/bpkg#43]
Hi, sorry if this is a noobish question, but I couldn't find anything in the docs on requiring a dependency. 

Is it as simple as setting the `dependencies` block in the `package.json` file? 

Suppose I'm writing a script that requires `mcrio/bashsh`. How do I configure my `package.json` to ensure that it will be included when my package is installed?

**Comment by jwerle** [comment]
We currently do not support it, but we'd happily accept a PR

**Comment by awei01** [comment]
Ok, thanks. I disclaim that I'm pretty new to writing bash scripts, though. But, I'll take a crack at it. 

Just some thoughts in terms of how to develop this feature:
1. Create a `bpkg-require` function that will update the `dependencies` block in the `package.json`
1. Update the `bpkg-install` to loop through the `dependencies` block and first check if the required package is installed globally. If it is, then skip it. If not, then install.

Thoughts?

**Comment by jwerle** [comment]
@awei01 that sounds good to me

**Comment by coderaiser** [comment]
>Update the bpkg-install to loop through the dependencies block and first check if the required package is installed globally. If it is, then skip it. If not, then install.

Would be better to separate local and global install to prevent version conflicts, like it npm does.

**Comment by hydra1983** [comment]
GH-94 ```__load "${BASH_SOURCE[0]}" "deps/shcore/shcore"```

**Comment by hydra1983** [comment]
@awei01 Should this issue be closed?
