### ISSUE TITLE
Consolidate materials needed for contributing

### ISSUE THREAD

**Issue by rylnd** [bpkg/bpkg#44]
In trying to add a project to bpkg, I had to pull materials from several sources (n.b. I'm still not sure that this list is complete/correct):
- [package details](https://github.com/bpkg/bpkg#package-details) section was the only place I found that referenced exactly what a project needed to be compatible with bpkg
- [submission instructions](http://www.bpkg.io/submit/) told me how to get my package listed, but was incomplete: 
  - I needed to refer to [the site](https://github.com/bpkg/bpkg.github.io)'s README to know that you were using jekyll (maybe you could add a Gemfile?)
  - the instructions tell you to clone locally and create a branch, but you won't be able to push that back to the remote :wink:

It would be really nice if all of this were consolidated to (or at least linked in) something like a CONTRIBUTING.md file.

If you agree, I'd be more than happy to help.

**Comment by jwerle** [comment]
+1 for sure. We've needed this for a while

**Comment by jwerle** [comment]
@rylnd did we want to create a  file still ?

**Comment by rylnd** [comment]
Hey @jwerle, sorry for the slow response. I'll reacquaint myself with the project's state and try to get something out this week.

**Comment by jwerle** [comment]
@rylnd awesome man, sounds good

**Comment by Potherca** [comment]
FYI: The package details section was added to the bpkg.io website with https://github.com/bpkg/bpkg.github.io/pull/34.

**Comment by Potherca** [comment]
Closing this for now. If it is still an issue, it can be reopened.
