### ISSUE TITLE
Do not depend on make

### ISSUE THREAD

**Issue by sschuberth** [bpkg/bpkg#45]
Some environments that can run Bash scripts do not ship with `make`, a typical example being the MSYS(2) based environments shipping with Git for Windows 1.x / 2.x. As such it would be nice to get rid of the dependency on `make`, e.g. by moving the targets from `Makefile` to functions in `install.sh`, and simply rely on `bash` instead of `make` to install the files.

**Comment by ccarpita** [comment]
Agree with the sentiment, as I haven't really been happy about the `make` dependency.  Would be in favor of a PR to remove this.

**Comment by sschuberth** [comment]
I'll take a look at it. Would you also be fine with renaming the `install.sh` script? Because calling e.g. `./install.sh uninstall` would be a bit odd, IMO. How about `setup.sh` or `bootstrap.sh`?

**Comment by ccarpita** [comment]
`setup.sh` sounds good to me!

**Comment by jwerle** [comment]
hehe I love this! LGTM! Good to see @ccarpita in this mix ! :D cc @wellsjo
