### ISSUE TITLE
Problems with installation instructions from source

### ISSUE THREAD

**Issue by abelsromero** [bpkg/bpkg#49]
Hi,

I tried to insall from source and when I execute `setup.sh` I get the folowing result

```
setup.sh
  info: Welcome to the 'bpkg' installer!
  info: Checking for git...

  info: Creating temporary files...
  info: Fetching latest 'bpkg'...
./setup.sh: línea 52: cd: /tmp/bpkg-master: No such file or directory
  info: Installing...

  info: Uninstalling /usr/local/bin/bpkg...
  info: Installing /usr/local/bin/bpkg...
./setup.sh: línea 72: bpkg: No such file or directory
install: no se puede efectuar `stat' sobre «bpkg»: No such file or directory
./setup.sh: línea 75: bpkg-json: No such file or directory
install: no se puede efectuar `stat' sobre «bpkg-json»: No such file or directory
./setup.sh: línea 75: bpkg-install: No such file or directory
install: no se puede efectuar `stat' sobre «bpkg-install»: No such file or directory
./setup.sh: línea 75: bpkg-package: No such file or directory
install: no se puede efectuar `stat' sobre «bpkg-package»: No such file or directory
./setup.sh: línea 75: bpkg-term: No such file or directory
install: no se puede efectuar `stat' sobre «bpkg-term»: No such file or directory
./setup.sh: línea 75: bpkg-suggest: No such file or directory
install: no se puede efectuar `stat' sobre «bpkg-suggest»: No such file or directory
./setup.sh: línea 75: bpkg-init: No such file or directory
install: no se puede efectuar `stat' sobre «bpkg-init»: No such file or directory
./setup.sh: línea 75: bpkg-utils: No such file or directory
install: no se puede efectuar `stat' sobre «bpkg-utils»: No such file or directory
./setup.sh: línea 75: bpkg-update: No such file or directory
install: no se puede efectuar `stat' sobre «bpkg-update»: No such file or directory
./setup.sh: línea 75: bpkg-list: No such file or directory
install: no se puede efectuar `stat' sobre «bpkg-list»: No such file or directory
./setup.sh: línea 75: bpkg-show: No such file or directory
install: no se puede efectuar `stat' sobre «bpkg-show»: No such file or directory
  info: Done!

```

Env: Win7 + cygwin

**Comment by abelsromero** [comment]
Btw, instructions here in github and on the site (http://www.gdub.rocks/) are different :crying_cat_face:

**Comment by ccarpita** [comment]
@abelsromero Out of curiosity is the following directory in your `$PATH` variable? -- `/usr/local/bin` -- We might have to prepend `$PATH` to some of the subshell calls in `setup.sh`

**Comment by abelsromero** [comment]
Yes, `/usr/local/bin` is in the path. But I don't understand the second part of your comment.
I looked into script and I found those likes quite weird: https://github.com/bpkg/bpkg/blob/master/setup.sh#L47-49

Is it me, or the temp folder is never created and then deleted?

**Comment by keen99** [comment]
@abelsromero just to clarify what setup is doing (because I was looking at it..)

    TMPDIR=${TMPDIR:-/tmp}
....
    cd "${TMPDIR}"
    echo "  info: Creating temporary files..."
    test -d "${DEST}" && { echo "  warn: Already exists: '${DEST}'"; }
    rm -rf "${DEST}"
    echo "  info: Fetching latest 'bpkg'..."
    git clone --depth=1 "${REMOTE}" "${DEST}" > /dev/null 2>&1
    cd "${DEST}"
...


this assumes TMPDIR exists - and since it's /tmp,  of course shouldn't delete it. 

DEST seems to be what you're asking about - in which case the delete is -f - easy way to "delete if it exists" instead of doing an actual test.   

DEST gets created with the git clone.

....then never deleted until next run (which triggers a warning..).   does seem like it should be removed after make_install.
