### ISSUE TITLE
get.bpkg.io broken?

### ISSUE THREAD

**Issue by nfarrar** [bpkg/bpkg#51]
get.bpkg.io broken?

    $ curl get.bpkg.io
    <html>
    <head><title>302 Found</title></head>
    <body bgcolor="white">
    <center><h1>302 Found</h1></center>
    <hr><center>nginx</center>
    </body>
    </html>

**Comment by ccarpita** [comment]
@jwerle I know you don't have time these days, but would it be straightforward to fixup the 302 from get.bpkg.io to point to setup.sh instead of install.sh, or is there anyway I can access this?

**Comment by jwerle** [comment]
@ccarpita I've updated the dns host record. It should propagate shortly!

**Comment by jwerle** [comment]
DNS is updated `curl -Lso- get.bpkg.io | bash` should work

**Comment by ccarpita** [comment]
Thanks @jwerle !   Love those fancy `URL` records :)
