### ISSUE TITLE
User override for 'deps/' directory?

### ISSUE THREAD

**Issue by nfarrar** [bpkg/bpkg#53]
It looks like the location of `deps` [is hardcoded](https://github.com/bpkg/bpkg/blob/29da5cf07f400b792388b7528668d913b7b9c410/lib/install/install.sh#L339). Would it be possible to make this configurable? Specifically, I'd like to make bpkg-installed dependencies install somewhere outside of `$HOME` (to keep it uncluttered) - specifically I'd like to install them to `~/.local/lib/<pkg>`.

**Comment by ccarpita** [comment]
Makes sense to me, and sounds like a good idea -- I would approve a PR for this change.

**Comment by tunnckoCore** [comment]
:+1: i'll send a PR when i can

**Comment by Potherca** [comment]
If no-one else is (still) working on this, I'd like to take a shot at it...

**Comment by tunnckoCore** [comment]
@Potherca go for it :)

**Comment by Potherca** [comment]
I've got a first working draft here: https://github.com/potherca-contrib/bpkg/pull/1/files

Once #81 has been merged I plan to open a PR for these changes here.

Until that time, I would be very grateful for any feedback...

**Comment by Potherca** [comment]
@nfarrar Just to make sure I understand what's expected, are you talking about global install, local install or both?

**Comment by Potherca** [comment]
Before picking up  other issues (mostly QA and cross-platform compatibility issues, specifically #90, #78 and #72) I would like to get my work for this issue finished (either merged or, worst case, thrown away).

Could anyone take a look at https://github.com/potherca-contrib/bpkg/pull/1/files to see if it matches the desired implementation. I'm also waiting for an answer to the question "global install, local install or both?".

**Comment by hydra1983** [comment]
@nfarrar See GH-94

**Comment by Potherca** [comment]
Closing this as it has been implemented in #140 

You can now override where dependencies are installed on a _per-project basis_ by setting  `BPKG_DEPS` (which is `./deps/` by default).
