### ISSUE TITLE
Bug during init procedure

### ISSUE THREAD

**Issue by michelezamuner** [bpkg/bpkg#57]
Here:

https://github.com/bpkg/bpkg/blob/master/lib/init/init.sh#LC240

should be `${NAME}`. This causes a "file not found" error at the end of the init procedure.

**Comment by jwerle** [comment]
@michelezamuner good catch

**Comment by jwerle** [comment]
Fixed with https://github.com/bpkg/bpkg/commit/7cc8b1e126898853794b0fe4337a985db261765a
