### ISSUE TITLE
Mismatched versions (0.2.7 vs 0.2.8)

### ISSUE THREAD

**Issue by thoward** [bpkg/bpkg#59]
Currently the `bpkg.sh` specifies `0.2.7` while `package.json` specifies `0.2.8`. 

Relevant lines of code: 
- https://github.com/bpkg/bpkg/blob/master/bpkg.sh#L10
- https://github.com/bpkg/bpkg/blob/master/package.json#L3

I assume this just needs a version bump in `bpkg.sh` to fix?

**Comment by jwerle** [comment]
Oops. Yep, exactly.
