### ISSUE TITLE
benefits over npm?

### ISSUE THREAD

**Issue by jasonkarns** [bpkg/bpkg#60]
Since npm isn't limited to javascript modules (it can install any package of files and works perfectly well for shell utilities and libs), I'm wondering what benefits bpkg has over straight npm?

I ask because I already use npm for a couple bash utilities (like bats, bats-assert and bats-mock) and it works marvelously. (pulling from github arguably makes more sense than publishing the package to npm, but still, using npm+package.json for installation works great). We are attempting to make a more official set of bats helper libs, and are contemplating supporting both.

Are there features of bpkg that make it preferable over just using npm?

**Comment by jwerle** [comment]
Hey @jasonkarns,

No, there isn't a real benefit to using bpkg over npm
