### ISSUE TITLE
Installing $HOME

### ISSUE THREAD

**Issue by gutierri** [bpkg/bpkg#76]
I think I could have a local installation, simple and global. The local installation behaves as dependencies and more staps are required to install.

What do you think?

It could behave like:

`bpkg install term --user` for example

(refs #74 #75 )

**Comment by pepa65** [comment]
Or you can do: `PREFIX=~ bpkg install term`

**Comment by gutierri** [comment]
@pepa65 Having an option like pip (--user) by default would be fine.

**Comment by pepa65** [comment]
I think it is (was?) supposed to work like that. `bpkg install term -g` does a global install, and without -g/--global it should be local. But the makefile in each package also needs to support this...

**Comment by hydra1983** [comment]
@pepa65 Without ```-g``` will be installed in ```pwd``` See GH-94

**Comment by vicentebolea** [comment]
@hydra1983 I believe that what @gutierri  and @pepa65  means is being able to install in `$HOME` by default.
Something like `PREFIX=~ bpkg install term` could be much more easily understood as `bpkg install -u/--user term` similarly to how it works with `pip`

+1

**Comment by jclaveau** [comment]
In Ubuntu (19.04 at least) ~/.profile contains

**Comment by jclaveau** [comment]
In Ubuntu (19.04 at least) ~/.profile contains
```
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
```

And using `.local` is first cleaner for your $HOME dir and is also more used by other programs:
```
ls ~/.local/lib/
android-studio-docker  docker-php-multiversion  python2.7  python3.7  shellspec
```
```
ls ~/.local/bin/
arduino  f2py  f2py2  f2py2.7  fluxgui  mid3cp  mid3iconv  mid3v2  moggsplit  mutagen-inspect  mutagen-pony  php  shellspec  xflux
```

**Comment by jclaveau** [comment]
Also, instead of adding an option, the target dir could be related to the user which is installing bpkg:
- root => /usr/local/bin
- $USER => $HOME/.local/bin

**Comment by gutierri** [comment]
That sounds good, but I don't know if I would still follow the project proposal. because it would have to change how to install packages in the current directory (PWD)

**Comment by jclaveau** [comment]
@gutierri What I suggest is only applied when the `-g` option is passed as you can see in the related PR:
https://github.com/bpkg/bpkg/pull/117

Behavior while installing in `pwd` remains exactly the same, whoever your are installing the package as.
