### ISSUE TITLE
bpkg install failure, basename: missing operand

### ISSUE THREAD

**Issue by aconthea** [bpkg/bpkg#82]
Hi, 

I am working on a shell project which I want to able to add as dependency using bpkg. Here is the package.json I have.

    {
      "name": "shelob",
      "version": "0.0.1",
      "description": "Bash utilities",
      "install": "utils/install.sh",
      "uninstall": "utils/uninstall.sh",
      "files":[ "shelob.sh" ],
      "scripts": []
    }

But when I try to add it as dependency to another project I get the following error:

     info: Install /breneser/shelob/master from remote https://raw.githubusercontent.com 
    [https://github.com]
    basename: missing operand
    Try 'basename --help' for more information.
    fetch: https://raw.githubusercontent.com/breneser/shelob/master/ shelob.sh
    write: /home/bren/projects/gitmek/deps/shelob/ shelob.sh

As you can see it seems to be trying to fetch the file with an extra space before the name. And it does not error. The  file it pulls saves github response which is `400: Invalid request`

**Comment by Potherca** [comment]
The error seems to originate from [install.sh:422](https://github.com/bpkg/bpkg/blob/2a30578d0b931704d96284c37bfa4c52eb0845a1/lib/install/install.sh#L422)

    local script="$(echo ${scripts[$i]} | xargs basename )"

Running the command below will show that the code is _always_ run, despite the array being empty:

    $ declare -a scripts="";for (( i = 0; i < ${#scripts[@]} ; ++i )); do \
        ( echo " --> ${i}: '${scripts[$i]}'" ) \
    done;
     --> 0: ''

There is no count/check on `scripts`, thus the error occurs.

As a short-term solution, removing `  "scripts": []` from the `package.json` should fix the error.
For the long-term a check could/should be added to make sure the code does not run if there is nothing to run the code _on_.

**Comment by breneser** [comment]
@Potherca It still errors with the same message even I delete scripts

**Comment by Potherca** [comment]
It looks like the `$scripts` array is still set to `""`, even if no "scripts" section is present in the `package.json`

I've taken the liberty to open a merge request #83 to resolve this issue.

**Comment by jhoblitt** [comment]
It isn't a work around for me but adding the `-g` will get past this failure by installing into` /usr/local/bin`.

**Comment by cha87de** [comment]
I stumbled across this wonderful bpkg software but I'm running into the install bug as well. As the merge request seems to solve at least parts of the problem (no `scripts` tag in package.json) I'm experiencing another bug when more than one elements are listed in the `scripts` array: the elements are not split correctly but occur as one string with line breaks for each element.

The merge request is from end of April and still open, which worries me a lot. Is this project here still alive? Before I start to seriously work with bpkg, I want to clarify that... I would be happy to contribute my own work of course.

**Comment by jwerle** [comment]
@cha87de bpkg is still very much alive. I've been busy and unable to work on it as much as I'd like. feel free to contribute. I'd happily merge a PR

**Comment by cha87de** [comment]
@jwerle great, here it comes ... ;-)

**Comment by cha87de** [comment]
@aconthea is the bug finally fixed? Can you quickly validate with the most recent version?

**Comment by aconthea** [comment]
@cha87de I actually kind of moved away from bpkg, haven't been using it. I will try this when I get a chance ( hopefully soon)

**Comment by cha87de** [comment]
@jwerle with the bug fixes it works (same for travis build #85 )

**Comment by jwerle** [comment]
@cha87de great! closing this now
