### ISSUE TITLE
Travis CI for automated testing

### ISSUE THREAD

**Issue by cha87de** [bpkg/bpkg#85]
To avoid bugs like issue #82 travis and continuous integration could help to automatically test the basic functionalities of bpkg. Opinions? PR will follow, in case you agree.

**Comment by cha87de** [comment]
If you like the idea, please review and merge PR #86.

**Comment by cha87de** [comment]
To enable travis, further manual actions may be necessary, to allow travis access to the repository.

**Comment by jwerle** [comment]
@cha87de i'll make you an owner

**Comment by cha87de** [comment]
@jwerle travis needs access to the repository to fix the build badge in the readme file. 
One with write permissions please go to https://travis-ci.org/bpkg/bpkg and enable the repo in travis. 
I would be happy to do that of course, if you provide me with enough permissions :-)

**Comment by jwerle** [comment]
@cha87de I have you write permission, I believe. Let me know if not !

**Comment by stephenmathieson** [comment]
iirc someone with admin permission has to enable travis. i'll do this now.

**Comment by stephenmathieson** [comment]
<img width="1046" alt="screen shot 2017-06-23 at 14 25 01" src="https://user-images.githubusercontent.com/571265/27501010-c3d0510a-581f-11e7-91c0-bd374c04a8fc.png">


=]

**Comment by jwerle** [comment]
:]

**Comment by cha87de** [comment]
Nice. Now we need a push to the repository to trigger travis.
