### ISSUE TITLE
http://bpkg.io doesn't redirect to www, and only the www site exists!

### ISSUE THREAD

**Issue by fluffywaffles** [bpkg/bpkg#88]
Hey bpkg maintainer(s), this project looks very cool, but unfortunately the link on the top of the repository page points to http://bpkg.io, which doesn't resolve! It would be ideal to have the naked domain redirect automatically to www.bpkg.io, but for now we can at least update the link. Thanks! :100:

**Comment by jwerle** [comment]
@fluffywaffles auto renewal failed. I'm in the middle of a support request to address this issue. I'll update when it is resolved

**Comment by fluffywaffles** [comment]
Sounds good! Thanks @jwerle

**Comment by jwerle** [comment]
@fluffywaffles bpkg.io was lost. we now own bpkg.sh, which makes more sense anyways ;)
