### ISSUE TITLE
Bash Installer broken due to domain change

### ISSUE THREAD

**Issue by cha87de** [bpkg/bpkg#91]
The following command doesn't work any more: `curl -sLo- http://get.bpkg.io | bash` - obviously because the domain got lost. Changing to the new domain `http://get.bpkg.sh` doesn't work either, probably because the subdomain is not existing in the DNS server. Can this be fixed please?
Thanks in advance!

**Comment by jwerle** [comment]
@cha87de fixed!

**Comment by cha87de** [comment]
Thanks for the fast fix! For consistency reasons, it would be cool to change also the website:
https://github.com/bpkg/bpkg.github.io/pull/40
