### ISSUE TITLE
Unable to find package.json

### ISSUE THREAD

**Issue by Pawamoy** [bpkg/bpkg#95]
I try to install [shellm-shellman](https://github.com/shellm-org/shellm-shellman) with bpkg but I get this error: `error: Unable to find 'package.json' in /home/pawamoy/deps/shellm-shellman`. Besides it seems that the `files` directive is broken, look at these two lines:
```
fetch: https://raw.githubusercontent.com/shellm-org/shellm-shellman/master/ lib/shellman.sh
write: /home/pawamoy/deps/shellm-shellman/ lib/ lib/shellman.sh
```
What with the spaces :O ? I end up with that (note the space before lib):

```
$ ll
total 12K
drwxr-xr-x 2 pawamoy pawamoy 4.0K Nov 17 18:55  lib
-rwxr--r-- 1 pawamoy pawamoy   15 Nov 17 18:55 shellm-generate-manpages
-rwxr--r-- 1 pawamoy pawamoy   15 Nov 17 18:55 shellm-generate-wikipages
```

... and nothing in ` lib`.

Here is my package.json:

```json
{
  "name": "shellm-shellman",
  "version": "0.0.1",
  "description": "Shellman for Shellm.",
  "global": "true",
  "install": "./install.sh ${PREFIX:-/usr/local}",
  "scripts": [
    "bin/shellm-generate-manpages",
    "bin/shellm-generate-wikipages"
  ],
  "files": ["lib/shellman.sh"],
  "dependencies": {}
}
```

Located at https://github.com/shellm-org/shellm-shellman/blob/master/package.json.

Full error log:

```bash
$ bpkg install shellm-org/shellm-shellman

    info: Install /shellm-org/shellm-shellman/master from remote https://raw.githubusercontent.com [https://github.com]
error: Unable to find `package.json' in /home/pawamoy/deps/shellm-shellman
    fetch: https://raw.githubusercontent.com/shellm-org/shellm-shellman/master/shellm-generate-manpages
    write: /home/pawamoy/deps/shellm-shellman/shellm-generate-manpages
    shellm-generate-manpages to PATH: /home/pawamoy/deps/bin/shellm-generate-manpages
    fetch: https://raw.githubusercontent.com/shellm-org/shellm-shellman/master/shellm-generate-wikipages
    write: /home/pawamoy/deps/shellm-shellman/shellm-generate-wikipages
    shellm-generate-wikipages to PATH: /home/pawamoy/deps/bin/shellm-generate-wikipages
    fetch: https://raw.githubusercontent.com/shellm-org/shellm-shellman/master/ lib/shellman.sh
    write: /home/pawamoy/deps/shellm-shellman/ lib/ lib/shellman.sh
```

**Comment by hydra1983** [comment]
![image](https://user-images.githubusercontent.com/488235/33230089-6d6a8a0e-d1a2-11e7-81aa-4d583351799f.png)

Seems there is no ```package.json```, only one file named ```package.sh```

**Comment by Pawamoy** [comment]
Yes, I removed it since then... I will put it back so we can reproduce

**Comment by Potherca** [comment]
The `files` problem seem to be caused by a bug that was introduced when I did a cleanup in #81.

The `Unable to find 'package.json'` occurs when `bpkg` tries to install the sub-dependencies (dependencies of the main package being installed).  As a message to clarify this is not given it looks like something has gone wrong. 

I have opened a MR (#99) to fix these issues.
